//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.12 at 02:11:49 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/core")
package ro.ulbsibiu.acaps.ctg.xml.core;
