//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.24 at 11:51:20 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webspace.ulbsibiu.ro/ciprian.radu/research/noc/application_mapping/unified_framework/schema/mapping", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ro.ulbsibiu.acaps.ctg.xml.mapping;
