//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.07 at 02:34:29 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/ctg", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ro.ulbsibiu.acaps.ctg.xml.ctg;
