//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 03:25:42 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/task")
package ro.ulbsibiu.acaps.ctg.xml.task;
